"""Contracts for the Codex runtime image import bridge."""

from __future__ import annotations

import base64
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from schemas.artifacts import validate_artifact
from tools.base_tool import BaseTool, ToolResult, ToolStatus
from tools.graphics.codex_image_import import CodexImageImport
from tools.tool_registry import ToolRegistry


PNG_1X1 = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII="
)


def test_codex_image_import_contract_identity():
    tool = CodexImageImport()

    assert issubclass(CodexImageImport, BaseTool)
    assert tool.name == "codex_image_import"
    assert tool.capability == "asset_import"
    assert tool.provider == "codex_runtime"
    assert tool.get_status() == ToolStatus.AVAILABLE
    assert "source_path" in tool.input_schema["required"]
    assert "asset_manifest_entry" in tool.capabilities


def test_codex_image_import_creates_schema_valid_asset_entry(tmp_path):
    source = tmp_path / "codex-output.png"
    source.write_bytes(PNG_1X1)
    project_dir = tmp_path / "project"

    result = CodexImageImport().execute(
        {
            "source_path": str(source),
            "project_dir": str(project_dir),
            "asset_id": "scene-001-keyframe",
            "scene_id": "scene-001",
            "prompt": "A clean comic-drama keyframe.",
            "generation_summary": "Generated by Codex runtime image tool during asset review.",
        }
    )

    assert isinstance(result, ToolResult)
    assert result.success, result.error
    assert result.data["copied"] is True
    assert (project_dir / "assets/images/scene-001-keyframe.png").exists()

    asset_entry = result.data["asset_entry"]
    assert asset_entry["source_tool"] == "codex_image_import"
    assert asset_entry["provider"] == "codex_runtime"
    assert asset_entry["path"] == "assets/images/scene-001-keyframe.png"

    validate_artifact(
        "asset_manifest",
        {
            "version": "1.0",
            "assets": [asset_entry],
            "total_cost_usd": 0.0,
        },
    )


def test_codex_image_import_missing_source_fails(tmp_path):
    result = CodexImageImport().execute(
        {
            "source_path": str(tmp_path / "missing.png"),
            "asset_id": "missing",
            "scene_id": "scene-001",
        }
    )

    assert isinstance(result, ToolResult)
    assert not result.success
    assert "source_path" in result.error


def test_codex_image_import_is_not_an_image_generation_provider():
    registry = ToolRegistry()
    registry.discover("tools")

    assert registry.get("codex_image_import") is not None
    assert "codex_image_import" not in {
        tool.name for tool in registry.get_by_capability("image_generation")
    }
    assert "codex_image_import" in {
        tool.name for tool in registry.get_by_capability("asset_import")
    }
