"""Import Codex-runtime generated images into an OpenMontage project.

Codex image generation is exposed to the agent runtime, not as a local Python
API. This tool intentionally does not generate images. It records an image that
the agent already created through the Codex runtime and makes it usable by the
normal OpenMontage asset_manifest -> edit -> compose flow.
"""

from __future__ import annotations

import re
import shutil
import time
from pathlib import Path
from typing import Any

from tools.base_tool import (
    BaseTool,
    Determinism,
    ExecutionMode,
    ResourceProfile,
    ToolResult,
    ToolRuntime,
    ToolStability,
    ToolStatus,
    ToolTier,
)


class CodexImageImport(BaseTool):
    name = "codex_image_import"
    version = "0.1.0"
    tier = ToolTier.SOURCE
    capability = "asset_import"
    provider = "codex_runtime"
    stability = ToolStability.BETA
    execution_mode = ExecutionMode.SYNC
    determinism = Determinism.DETERMINISTIC
    runtime = ToolRuntime.HYBRID

    dependencies: list[str] = []
    install_instructions = (
        "No API key is required. Generate the image through the active Codex "
        "runtime first, save it to a local file, then import that file with "
        "this tool."
    )
    agent_skills: list[str] = []

    capabilities = [
        "import_codex_runtime_image",
        "copy_external_image",
        "asset_manifest_entry",
        "zero_key_image_workflow",
    ]
    supports = {
        "requires_agent_runtime": True,
        "calls_codex_image_tool": False,
        "batch_unattended_generation": False,
        "asset_manifest_entry": True,
        "copies_to_project_assets": True,
    }
    best_for = [
        "zero-key workflows where Codex creates still images during the session",
        "turning Codex-generated illustrations into pipeline assets",
        "preserving prompt and provenance in asset_manifest entries",
    ]
    not_good_for = [
        "unattended batch image generation",
        "running outside an agent runtime that can create images",
        "selector-based provider routing",
    ]

    input_schema = {
        "type": "object",
        "required": ["source_path", "asset_id", "scene_id"],
        "properties": {
            "source_path": {
                "type": "string",
                "description": "Local file path of the image already generated by the Codex runtime.",
            },
            "asset_id": {
                "type": "string",
                "description": "Stable asset id to use in asset_manifest and edit_decisions.",
            },
            "scene_id": {
                "type": "string",
                "description": "Scene id this image belongs to.",
            },
            "project_dir": {
                "type": "string",
                "description": "Project workspace, e.g. projects/my-video. Used for relative manifest paths.",
            },
            "output_path": {
                "type": "string",
                "description": "Optional destination path. Relative paths are resolved under project_dir.",
            },
            "prompt": {
                "type": "string",
                "description": "Prompt used with the Codex runtime image tool.",
            },
            "generation_summary": {
                "type": "string",
                "description": "Short provenance note or visual summary.",
            },
            "model": {
                "type": "string",
                "default": "codex-runtime-image-tool",
            },
            "subtype": {
                "type": "string",
                "default": "codex_runtime_generated",
            },
            "copy": {
                "type": "boolean",
                "default": True,
                "description": "Copy the source image into the project assets directory.",
            },
            "overwrite": {
                "type": "boolean",
                "default": False,
                "description": "Allow replacing an existing destination file.",
            },
        },
    }

    output_schema = {
        "type": "object",
        "properties": {
            "asset_entry": {"type": "object"},
            "output": {"type": "string"},
            "copied": {"type": "boolean"},
            "inspection": {"type": "object"},
        },
    }

    resource_profile = ResourceProfile(
        cpu_cores=1,
        ram_mb=128,
        vram_mb=0,
        disk_mb=100,
        network_required=False,
    )
    idempotency_key_fields = ["source_path", "asset_id", "scene_id", "output_path"]
    side_effects = ["copies image file to project assets", "returns asset_manifest entry"]
    user_visible_verification = [
        "Inspect the imported image for prompt match, style consistency, and framing",
        "Confirm the asset_entry path exists before compose",
    ]

    def get_status(self) -> ToolStatus:
        return ToolStatus.AVAILABLE

    def execute(self, inputs: dict[str, Any]) -> ToolResult:
        start = time.time()

        try:
            source = Path(inputs["source_path"]).expanduser()
            if not source.is_file():
                return ToolResult(
                    success=False,
                    error=f"source_path does not exist or is not a file: {source}",
                )

            asset_id = str(inputs["asset_id"]).strip()
            scene_id = str(inputs["scene_id"]).strip()
            if not asset_id:
                return ToolResult(success=False, error="asset_id is required")
            if not scene_id:
                return ToolResult(success=False, error="scene_id is required")

            project_dir = self._optional_path(inputs.get("project_dir"))
            destination = self._destination_path(
                source=source,
                asset_id=asset_id,
                project_dir=project_dir,
                output_path=inputs.get("output_path"),
            )

            should_copy = bool(inputs.get("copy", True))
            copied = False
            if should_copy and source.resolve() != destination.resolve():
                if destination.exists() and not inputs.get("overwrite", False):
                    return ToolResult(
                        success=False,
                        error=(
                            f"Destination already exists: {destination}. "
                            "Pass overwrite=true to replace it."
                        ),
                    )
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)
                copied = True
            else:
                destination = source

            inspection = self._inspect_image(destination)
            manifest_path = self._manifest_path(destination, project_dir)
            asset_entry = {
                "id": asset_id,
                "type": "image",
                "path": manifest_path,
                "source_tool": self.name,
                "scene_id": scene_id,
                "subtype": inputs.get("subtype", "codex_runtime_generated"),
                "provider": self.provider,
                "model": inputs.get("model", "codex-runtime-image-tool"),
                "cost_usd": 0.0,
            }

            prompt = inputs.get("prompt")
            if prompt:
                asset_entry["prompt"] = prompt

            generation_summary = inputs.get("generation_summary")
            if generation_summary:
                asset_entry["generation_summary"] = generation_summary
            else:
                asset_entry["generation_summary"] = (
                    "Image generated through the active Codex runtime and "
                    "imported for local OpenMontage composition."
                )

            if inspection.get("resolution"):
                asset_entry["resolution"] = inspection["resolution"]
            if inspection.get("format"):
                asset_entry["format"] = inspection["format"]

            return ToolResult(
                success=True,
                data={
                    "output": str(destination),
                    "copied": copied,
                    "asset_entry": asset_entry,
                    "inspection": inspection,
                    "provider": self.provider,
                    "source_tool": self.name,
                    "codex_runtime_note": (
                        "This tool imports a file created by Codex; it does "
                        "not call Codex image generation from Python."
                    ),
                },
                artifacts=[str(destination)],
                cost_usd=0.0,
                duration_seconds=round(time.time() - start, 2),
                model=asset_entry["model"],
            )
        except Exception as exc:
            return ToolResult(
                success=False,
                error=f"codex_image_import failed: {type(exc).__name__}: {exc}",
            )

    def _destination_path(
        self,
        *,
        source: Path,
        asset_id: str,
        project_dir: Path | None,
        output_path: str | None,
    ) -> Path:
        if output_path:
            destination = Path(output_path).expanduser()
            if not destination.is_absolute() and project_dir is not None:
                destination = project_dir / destination
            return destination

        if project_dir is not None:
            suffix = source.suffix if source.suffix else ".png"
            return project_dir / "assets" / "images" / f"{self._safe_filename(asset_id)}{suffix}"

        return source

    @staticmethod
    def _optional_path(value: Any) -> Path | None:
        if not value:
            return None
        return Path(str(value)).expanduser()

    @staticmethod
    def _safe_filename(value: str) -> str:
        safe = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip())
        return safe.strip(".-") or "codex-image"

    @staticmethod
    def _manifest_path(path: Path, project_dir: Path | None) -> str:
        if project_dir is not None:
            try:
                return str(path.resolve().relative_to(project_dir.resolve()))
            except ValueError:
                pass
        return str(path)

    @staticmethod
    def _inspect_image(path: Path) -> dict[str, Any]:
        suffix_format = path.suffix.lower().lstrip(".") or "unknown"
        try:
            from PIL import Image

            with Image.open(path) as image:
                width, height = image.size
                image_format = (image.format or suffix_format).lower()
            return {
                "width": width,
                "height": height,
                "resolution": f"{width}x{height}",
                "format": image_format,
            }
        except Exception as exc:
            return {
                "format": suffix_format,
                "inspection_warning": f"Could not inspect image dimensions: {type(exc).__name__}",
            }
